% CH03-VISUALIZATION
%
% Files
%   Mug.jpg           - Source image of a mug
%
% Functions
%   createfigure      - CREATEFIGURE(X1, YVECTOR1) Autogenerated figure code.
%   Draftmark         - Add a draft marking to a figure. 
%   PlotPage          - Create a plot page with several custom plots in one figure.
%   QuadPlot          - Create a quad plot page using subplot.
%   Watermark         - Add a watermark to a figure. 
%
% Scripts
%   AnnotatePlot      - Create a plot and annotate it with text
%   BoxPatch          - Generate a cube using patch
%   ColorDistribution - Demonstrate a color distribution for an array of lines.
%   GridVisualization - Visualize data over 2D and 3D grids
%   PatchWithCamera   - Generate two cubes using patch and point a camera at the scene
%   PatchWithLighting - Add lighting to the cube patch
%   PlottingWithDates - Plot using months as the x label
%   ReadImage         - Draw a JPEG image in a figure multiple ways
%   SphereLighting    - Create and light a sphere
%

%   HeatMapDemo       - Heat map 
%   NewFigure         - Create a new named figure window
%   RandomWalk        - Demonstrate a digraph and graph

