function createfigure(X1, yvector1)
%CREATEFIGURE(X1, YVECTOR1) Autogenerated figure code.
%  X1:  area x
%  YVECTOR1:  area yvector

%  Auto-generated by MATLAB on 03-Jun-2015 14:32:43

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'XGrid','on','OuterPosition',[0 0.5 1 0.5]);
box(axes1,'on');
hold(axes1,'on');

% Create ylabel
ylabel('Data');

% Create xlabel
xlabel('Angle (rad)');

% Create title
title('Area Plot');

% Create area
area(X1,yvector1,'DisplayName','Area','Parent',axes1);

% Create axes
axes2 = axes('Parent',figure1,'OuterPosition',[0 0 1 0.5]);
box(axes2,'on');
hold(axes2,'on');

% Create ylabel
ylabel('Theta');

% Create xlabel
xlabel('Increment');

% Create stem
stem(X1,'DisplayName','theta','Parent',axes2,'Marker','none',...
  'Color',[0 0.447 0.741]);

% Create textarrow
annotation(figure1,'textarrow',[0.609822646657571 0.568894952251023],...
  [0.827828828828829 0.717117117117118]);

% Create textbox
annotation(figure1,'textbox',...
  [0.553888130968622 0.814895792699917 0.120787482806052 0.0489690721649485],...
  'String',{'Point of interest'});

